name: Test package installation

on:
  push:
    branches: [ develop, dev/*, release/* ]
  pull_request:
    branches: [ develop, dev/*, release/* ]
  workflow_dispatch:
    inputs:
      user-to-notify:
        description: "Github username to notify"
        required: false
        default: ""

jobs:
  standard-packages:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: [ '3.8', '3.9', '3.10', '3.11' ]
        os: [ubuntu-latest, macos-latest] #, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Get taipy-gui version from setup.py
        id: taipy_gui_version
        run: |
          echo """
          with open('setup.py') as f:
              for line in f:
                  if 'taipy-gui' in line:
                      start = line.find('taipy-gui')
                      end = line.rstrip().find('\",')
                      print(f'VERSION={line[start:end]}')
                      break
          """ > ${{ runner.temp }}/get_gui_version.py
          python ${{ runner.temp }}/get_gui_version.py >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install taipy-gui from based on setup.py version
          pip install "${{ steps.taipy_gui_version.outputs.VERSION }}"

      - name: Install Taipy without dependencies
        run: |
          pip install .
          rm -rf src

          python -c "import taipy as tp; tp.Scenario"
          python -c "import taipy as tp; tp.gui"
          python -c "import taipy as tp; tp.rest"

          echo """
          import taipy
          from pathlib import Path
          taipy_gui_core_path = Path(taipy.__file__).absolute().parent / 'gui_core' / 'lib' / 'taipy-gui-core.js'
          if not taipy_gui_core_path.exists():
              raise FileNotFoundError(f'taipy-gui-core.js not found in {taipy_gui_core_path}')
          """ > ${{ runner.temp }}/verify_gui_core.py
          python ${{ runner.temp }}/verify_gui_core.py

      - name: Notify user if failed
        if: failure()
        run: |
          if [[ -n "${{ github.event.inputs.user-to-notify }}" ]]; then
            curl "${{ secrets.notify_endpoint }}" -d '{"username": "${{ github.event.inputs.user-to-notify }}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' -H "Content-Type: application/json"
          fi
        shell: bash
